packages:
  - 'packages/*'

settings:
  strictPeerDependencies: false

catalog:
  '@changesets/cli': '^2.27.9'
  # stylelint-config dependencies
  '@stylistic/stylelint-config': '^5.0.0'
  'stylelint': '^17.6.0'
  'stylelint-config-property-sort-order-smacss': '^11.2.0'
  'stylelint-config-recommended': '^18.0.0'
  'stylelint-config-recommended-scss': '^17.0.0'
  'stylelint-config-recommended-vue': '^1.6.1'
  'stylelint-order': '^8.1.1'
  'stylelint-prettier': '^5.0.3'
  'stylelint-scss': '^7.0.0'
  'postcss-html': '^1.8.1'
  'postcss-scss': '^4.0.9'
  # build tools
  '@types/node': '^22.13.10'
  '@types/lodash-es': '^4.17.12'
  'typescript': '^5.8.2'
  'tsup': '^8.4.0'
  'rimraf': '^6.0.1'
  # vite & plugins
  'vite': '^6.2.1'
  '@vitejs/plugin-vue': '^5.0.4'
  '@vitejs/plugin-vue-jsx': '^4.1.1'
  'vite-plugin-html': '^3.2.0'
  'vite-plugin-top-level-await': '^1.5.0'
  'vite-plugin-vue-meta-layouts': '^0.5.1'
  'vite-plugin-vue-setup-extend': '^0.4.0'
  # unplugin ecosystem
  'unplugin-auto-import': '^19.1.1'
  'unplugin-icons': '^22.1.0'
  'unplugin-vue-components': '^28.4.1'
  'unplugin-vue-router': '^0.12.0'
  # unocss
  'unocss': '^66.1.0-beta.3'
  '@unocss/transformer-directives': '^66.1.0-beta.3'
  '@unocss/transformer-variant-group': '^66.1.0-beta.3'
  # utilities
  'lodash-es': '^4.17.21'
  'rollup-plugin-visualizer': '^5.14.0'
  # eslint-config dependencies
  '@stylistic/eslint-plugin': '^5.10.0'
  '@types/eslint': '^9.6.1'
  '@types/eslint-config-prettier': '^6.11.3'
  '@typescript-eslint/eslint-plugin': '^8.58.0'
  '@typescript-eslint/parser': '^8.58.0'
  '@unocss/eslint-config': '^66.6.7'
  'eslint': '^10.1.0'
  'eslint-config-flat-gitignore': '^2.3.0'
  'eslint-config-prettier': '^10.1.5'
  'eslint-flat-config-utils': '^3.1.0'
  '@eslint-community/eslint-plugin-eslint-comments': '^4.7.1'
  'eslint-plugin-import-x': '^4.16.2'
  'eslint-plugin-jsdoc': '^62.9.0'
  'eslint-plugin-jsonc': '^3.1.2'
  '@eslint/markdown': '^8.0.1'
  'eslint-plugin-n': '^17.24.0'
  'eslint-plugin-perfectionist': '^5.8.0'
  'eslint-plugin-prettier': '^5.5.5'
  'eslint-plugin-unicorn': '^64.0.0'
  'eslint-plugin-unused-imports': '^4.4.1'
  'eslint-plugin-vue': '^10.8.0'
  'eslint-merge-processors': '^2.0.0'
  '@e18e/eslint-plugin': '^0.3.0'
  'eslint-plugin-pnpm': '^1.6.0'
  'eslint-plugin-regexp': '^3.1.0'
  'eslint-plugin-vuejs-accessibility': '^2.5.0'
  'eslint-processor-vue-blocks': '^2.0.0'
  'eslint-typegen': '^2.0.0'
  'esno': '^4.8.0'
  'globals': '^17.4.0'
  'jsonc-eslint-parser': '^3.1.0'
  'prettier': '^3.8.1'
  'vue-eslint-parser': '^10.4.0'
